import { config } from "dotenv";
import { z } from "zod";

config();

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  BACKEND_PORT: z.coerce.number().int().positive().default(3000),
  ENFORCE_SINGLE_SESSION: z.coerce.boolean().default(true),
  STORAGE_PATH: z.string().default("storage"),
  PROMETHEUS_METRICS_ENABLED: z.coerce.boolean().default(false),
  PROMETHEUS_METRICS_TOKEN: z.string().optional(),
  SENTRY_DSN: z.string().optional(),
  SENTRY_ENVIRONMENT: z.string().optional(),
  SENTRY_RELEASE: z.string().optional(),
  SENTRY_TRACES_SAMPLE_RATE: z.coerce.number().min(0).max(1).optional(),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  REDIS_KEY_PREFIX: z.string().default(""),
  FRONTEND_URL: z.string().url(),
  JWT_ACCESS_SECRET: z.string().min(32),
  JWT_REFRESH_SECRET: z.string().min(32),
  VIDEO_TOKEN_SECRET: z.string().min(32),
  PAYMOB_API_KEY: z.string().min(1),
  PAYMOB_HMAC_SECRET: z.string().min(1),
  PAYMOB_INTEGRATION_ID: z.string().min(1),
  PAYMOB_IFRAME_ID: z.string().min(1),
  GOOGLE_CLIENT_ID: z.string().min(1),
  GOOGLE_CLIENT_SECRET: z.string().min(1),
  SMTP_HOST: z.string().min(1),
  SMTP_PORT: z.coerce.number().int().positive(),
  SMTP_USER: z.string().min(1),
  SMTP_PASS: z.string().min(1),
  HCAPTCHA_SECRET_KEY: z.string().min(1).default("placeholder_hcaptcha_secret"),
  CACHE_TTL_DASHBOARD_SECONDS: z.coerce.number().int().positive().default(5 * 60),
  CACHE_TTL_ENROLLMENT_SECONDS: z.coerce.number().int().positive().default(2 * 60),
  CACHE_TTL_LESSON_METADATA_SECONDS: z.coerce.number().int().positive().default(2 * 60 * 60),
  CACHE_TTL_PUBLISHED_LESSON_COUNT_SECONDS: z.coerce.number().int().positive().default(2 * 60 * 60),
  CACHE_TTL_PAYMENTS_SECONDS: z.coerce.number().int().positive().default(60 * 60),
  CACHE_TTL_VIDEO_TOKEN_SECONDS: z.coerce.number().int().positive().default(5 * 60),
  CACHE_TTL_VIDEO_PREVIEW_SECONDS: z.coerce.number().int().positive().default(15 * 60),
  CACHE_TTL_SEARCH_SECONDS: z.coerce.number().int().positive().default(300),
  DEFAULT_COURSE_ID: z.string().default("primary"),
  UPLOAD_FEATURE_ENABLED: z.coerce.boolean().default(true),
  UPLOAD_PROTOCOL: z.enum(["TUS", "MULTIPART"]).default("TUS"),
  UPLOAD_STORAGE_PROVIDER: z.enum(["S3", "R2", "MINIO", "LOCAL"]).default("S3"),
  UPLOAD_STORAGE_BUCKET: z.string().default("eduflow-media"),
  UPLOAD_ALLOWED_MIME_TYPES: z.string().default(
    "video/mp4,video/quicktime,video/webm,video/x-msvideo,video/x-matroska,image/jpeg,image/png,image/gif,image/webp,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/zip,application/x-zip-compressed,text/plain"
  ),
  UPLOAD_MAX_FILE_SIZE_BYTES: z.coerce.number().int().positive().default(5 * 1024 * 1024 * 1024),
  UPLOAD_MIN_CHUNK_SIZE_BYTES: z.coerce.number().int().positive().default(1 * 1024 * 1024),
  UPLOAD_DEFAULT_CHUNK_SIZE_BYTES: z.coerce.number().int().positive().default(2 * 1024 * 1024),
  UPLOAD_MAX_CHUNK_SIZE_BYTES: z.coerce.number().int().positive().default(20 * 1024 * 1024),
  UPLOAD_MAX_CONCURRENCY: z.coerce.number().int().positive().default(2),
  UPLOAD_MAX_RETRY_ATTEMPTS: z.coerce.number().int().nonnegative().default(3),
  UPLOAD_RETRY_INITIAL_DELAY_SECONDS: z.coerce.number().int().positive().default(5),
  UPLOAD_RETRY_MAX_DELAY_SECONDS: z.coerce.number().int().positive().default(30),
  UPLOAD_SESSION_TTL_SECONDS: z.coerce.number().int().positive().default(24 * 60 * 60),
  UPLOAD_CHECKPOINT_TTL_SECONDS: z.coerce.number().int().positive().default(7 * 24 * 60 * 60),
  UPLOAD_SIGNED_URL_TTL_SECONDS: z.coerce.number().int().positive().default(15 * 60),
  UPLOAD_QUEUE_STUCK_THRESHOLD_SECONDS: z.coerce.number().int().positive().default(10 * 60)
});

export const env = envSchema.parse(process.env);
