// Payment and order statuses - use these instead of hardcoded strings
export const PAYMENT_STATUS = {
  INITIATED: "INITIATED",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
  WEBHOOK_PENDING: "WEBHOOK_PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  ENROLLMENT_FAILED: "ENROLLMENT_FAILED",
  EMAIL_FAILED: "EMAIL_FAILED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUNDED: "REFUNDED",
  REFUND_FAILED: "REFUND_FAILED",
  DISPUTED: "DISPUTED",
  MANUAL_OVERRIDE: "MANUAL_OVERRIDE"
} as const;

export type PaymentStatus = typeof PAYMENT_STATUS[keyof typeof PAYMENT_STATUS];

export const PAYMENT_STATUS_VALUES = Object.values(PAYMENT_STATUS);

export const PAYMENT_EVENT_TYPE = {
  INITIATED: "INITIATED",
  PAYMENT_KEY_GENERATED: "PAYMENT_KEY_GENERATED",
  PAYMOB_API_ERROR: "PAYMOB_API_ERROR",
  WEBHOOK_RECEIVED: "WEBHOOK_RECEIVED",
  WEBHOOK_VERIFIED: "WEBHOOK_VERIFIED",
  WEBHOOK_DUPLICATE: "WEBHOOK_DUPLICATE",
  STATUS_CHANGED: "STATUS_CHANGED",
  ENROLLMENT_TRIGGERED: "ENROLLMENT_TRIGGERED",
  ENROLLMENT_SUCCEEDED: "ENROLLMENT_SUCCEEDED",
  ENROLLMENT_FAILED: "ENROLLMENT_FAILED",
  EMAIL_QUEUED: "EMAIL_QUEUED",
  EMAIL_SENT: "EMAIL_SENT",
  EMAIL_FAILED: "EMAIL_FAILED",
  COUPON_INCREMENTED: "COUPON_INCREMENTED",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_API_CALL: "REFUND_API_CALL",
  REFUND_SUCCEEDED: "REFUND_SUCCEEDED",
  REFUND_FAILED: "REFUND_FAILED",
  DISPUTE_RECEIVED: "DISPUTE_RECEIVED",
  MANUAL_OVERRIDE_APPLIED: "MANUAL_OVERRIDE_APPLIED"
} as const;

export type PaymentEventType = typeof PAYMENT_EVENT_TYPE[keyof typeof PAYMENT_EVENT_TYPE];

export const ORDER_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED"
} as const;

export type OrderStatus = typeof ORDER_STATUS[keyof typeof ORDER_STATUS];

export const ORDER_STATUS_VALUES = Object.values(ORDER_STATUS);
