import type { AppLocale } from "@/lib/locale";

const en = {
  common: {
    all: "All",
    active: "Active",
    inactive: "Inactive",
    amount: "Amount",
    awaitingAdmin: "Awaiting admin",
    bodyHtml: "Body HTML",
    broadcast: "Broadcast",
    cancel: "Cancel",
    code: "Code",
    completed: "Completed",
    confirmBroadcast: "Confirm broadcast",
    coupon: "Coupon",
    createCoupon: "Create coupon",
    createFirstLesson: "Create the first lesson",
    delete: "Delete",
    draft: "Draft",
    edit: "Edit",
    editDetails: "Edit details",
    editPackage: "Edit package",
    egp: "EGP",
    failed: "Failed",
    loading: "Loading...",
    markPaid: "Mark as paid",
    noSubject: "No subject yet",
    pending: "Pending",
    published: "Published",
    ready: "Ready",
    refunded: "Refunded",
    resolved: "Resolved",
    savePackage: "Save package",
    sendReply: "Send reply",
    sending: "Sending...",
    status: "Status",
    subject: "Subject",
    updating: "Updating...",
    used: "used"
  },
  lessons: {
    totalLessons: "Total lessons",
    filteredLessons: "Lessons in selected section",
    fullWorkspace: "Across the full course workspace",
    filteredWorkspace: "Filtered for the active section",
    videoReady: "Video ready",
    readyNote: "Lessons that are ready for students",
    processingNow: "Processing now",
    processingNote: "Uploads still being prepared",
    needsPublishing: "Needs publishing",
    needsPublishingNote: "Draft lessons still hidden from students",
    workflow: "Workflow",
    workflowSteps: [
      "1. Choose a section to narrow the workspace.",
      "2. Create or select a lesson.",
      "3. Upload the lesson video and add attachments.",
      "4. Publish only when the lesson is fully ready."
    ],
    workspace: "Lesson workspace",
    manageSection: "Manage lessons for the active section",
    manageLibrary: "Manage the full lesson library",
    workspaceDesc: "Keep section structure, publish state, video readiness, and resource management in one place so lesson operations stay easy to scan.",
    showAll: "Show all",
    newLesson: "+ New lesson",
    emptySectionTitle: "No lessons in this section yet",
    emptyAllTitle: "No lessons created yet",
    emptySectionDesc: "This section is ready for content, but no lessons have been added yet.",
    emptyAllDesc: "Create your first lesson to start building the student learning path.",
    selectedLesson: "Selected lesson",
    noVideo: "No video",
    processing: "Processing",
    needsReview: "Needs review",
    noDuration: "No duration yet",
    noSection: "No section assigned",
    unsectioned: "Unsectioned",
    noDrip: "No drip delay",
    unlocksAfter: "Unlocks after {{days}} day(s)",
    order: "Order",
    duration: "Duration",
    release: "Release",
    visibility: "Visibility",
    immediate: "Immediate",
    dayDrip: "{{days}} day drip",
    editSettings: "Edit lesson settings",
    videoUpload: "Video upload",
    replaceVideo: "Replace or add the lesson video",
    uploadDesc: "Upload the final lesson recording here. Processing may take a little time before the lesson is fully ready.",
    videoFile: "Video file",
    uploadProgress: "Upload progress",
    cancelUpload: "Cancel upload",
    pickLessonTitle: "Pick a lesson to continue",
    pickLessonDesc: "Select a lesson from the workspace to upload media, review its status, and manage attachments."
  },
  orders: {
    totalOrders: "Total orders",
    totalOrdersNote: "Across the current admin feed",
    pendingReview: "Pending review",
    pendingReviewNote: "Orders still waiting for confirmation",
    failedNote: "Payments that likely need support follow-up",
    capturedRevenue: "Captured revenue",
    capturedRevenueNote: "Completed orders only",
    revenueOps: "Revenue operations",
    title: "Review exceptions first, then sweep the healthy orders",
    desc: "This workspace is optimized for payment follow-up. Pending and failed orders should stand out quickly so the clean completed payments do not hide the ones that need attention.",
    allOrders: "All orders",
    exportCsv: "Export CSV",
    emptyTitle: "No orders in this view",
    emptyDesc: "No orders match the current filter. Try switching back to all orders or review pending items first.",
    selectedOrder: "Selected order",
    orderId: "Order ID",
    date: "Date",
    recommended: "Recommended handling",
    recommendedDesc: "Mark orders as paid only after external confirmation from your payment dashboard or support workflow. Keep failed payments visible so the team can follow up or advise the student clearly.",
    pickTitle: "Pick an order to review",
    pickDesc: "Select an order to inspect its amount, status, and next action."
  },
  pricing: {
    activePackages: "Active packages",
    activePackagesNote: "Public offer currently visible to students",
    activeCoupons: "Active coupons",
    activeCouponsNote: "Live discounts still usable at checkout",
    couponRevenue: "Coupon revenue",
    couponRevenueNote: "Tracked revenue generated through coupon usage",
    pricingSurfaces: "Pricing surfaces",
    pricingSurfacesValue: "2 areas",
    pricingSurfacesNote: "Packages and coupons are managed separately",
    operations: "Pricing operations",
    title: "Keep the public offer clear, then layer coupons on top with intention",
    desc: "This page splits package management from coupon controls so the public offer stays easy to reason about and discounts do not get mixed into base pricing decisions.",
    coursePackages: "Course packages",
    publicOptions: "Public pricing options",
    newPackage: "+ New package",
    noPackages: "No course packages",
    noPackagesDesc: "No packages are configured yet. Add the first package to define the public offer.",
    sort: "Sort",
    couponPerformance: "Coupon performance",
    noCoupons: "No coupons created",
    noCouponsDesc: "No coupons are live yet. Create one when you want a targeted promotion or recovery offer.",
    revenueGenerated: "Revenue generated",
    createCouponTitle: "Add a targeted discount without changing the base offer",
    discountType: "Discount type",
    discountValue: "Discount value",
    maxUses: "Max uses",
    expiryDate: "Expiry date",
    percentage: "Percentage",
    fixed: "Fixed",
    percentageOff: "{{value}}% off",
    fixedOff: "{{value}} EGP off",
    editPackage: "Edit package",
    createPackage: "Create package",
    packageDialogDesc: "Update the public package offer without mixing it into coupon logic.",
    titleEn: "Title (EN)",
    titleAr: "Title (AR)",
    descriptionEn: "Description (EN)",
    descriptionAr: "Description (AR)",
    priceEgp: "Price (EGP)",
    sortOrder: "Sort order"
  },
  analytics: {
    revenue: "Revenue",
    revenueNote: "Current payment feed summary",
    completedNote: "Successful payments in the feed",
    failedNote: "Transactions that likely need review",
    insightWindow: "Insight window",
    insightWindowNote: "Current learning analytics period",
    view: "Analytics view",
    title: "Lead with decisions, not raw charts",
    desc: "These panels separate learning performance from payment follow-up so growth insights and revenue operations stay readable instead of competing for attention.",
    topLessons: "Top-performing lessons",
    noTopTitle: "No top-performing lessons yet",
    noTopDesc: "No lesson analytics are available for this period yet.",
    completion: "completion",
    avgWatch: "Avg. watch time",
    dropOff: "Lessons with drop-off",
    noDropTitle: "No drop-off risks detected",
    noDropDesc: "No drop-off lessons were returned for this period.",
    avgExit: "Avg. exit point",
    paymentReview: "Payment review",
    paymentTitle: "Keep exceptions visible and actionable",
    noPaymentsTitle: "No payments in this view",
    noPaymentsDesc: "No payments matched the current filter.",
    selectedPayment: "Selected payment",
    discount: "Discount",
    transaction: "Transaction",
    none: "None",
    notAvailable: "Not available",
    pickPaymentTitle: "Pick a payment to review",
    pickPaymentDesc: "Select a payment to inspect coupon usage, transaction details, and next actions."
  },
  tickets: {
    openTickets: "Open tickets",
    openTicketsNote: "Needs active support handling",
    resolvedNote: "Completed support threads",
    awaitingAdminNote: "Latest message came from the student",
    currentView: "Current view",
    currentViewNote: "Filtered support queue",
    supportQueue: "Support queue",
    title: "Put urgent student conversations at the top and keep reply flow fast",
    allTickets: "All tickets",
    emptyTitle: "No tickets to review",
    emptyDesc: "There are no tickets in this view right now.",
    updated: "Updated",
    triageNotes: "Triage notes",
    triage: [
      "Prioritize open tickets where the latest message came from the student.",
      "Resolve threads only after the student question has been answered clearly.",
      "Use the conversation panel to keep replies concise and operationally safe."
    ],
    details: "Ticket details",
    reply: "Reply",
    replyPlaceholder: "Write a clear, helpful response",
    resolveTicket: "Resolve ticket",
    noMessages: "No messages yet."
  },
  audit: {
    visibleEntries: "Visible entries",
    visibleEntriesNote: "Current results in this workspace",
    totalEntries: "Total entries",
    totalEntriesNote: "All audit events returned by the API",
    uniqueActors: "Unique actors",
    uniqueActorsNote: "Admins with logged activity",
    expandedRow: "Expanded row",
    expandedRowNote: "Detailed metadata currently open",
    workspace: "Audit workspace",
    title: "Review who changed what, and open metadata only when needed",
    desc: "This page is designed for quick investigation first and detailed metadata second, so the event stream stays readable even when the log grows.",
    searchLabel: "Search actor, action, or target",
    searchPlaceholder: "Search the audit feed",
    noMatchTitle: "No matching audit events",
    noMatchDesc: "No audit entries match the current search. Try a broader query or clear the filter.",
    time: "Time",
    actor: "Actor",
    action: "Action",
    target: "Target",
    metadata: "Metadata"
  },
  notifications: {
    templates: "Templates",
    templatesNote: "Reusable notification building blocks",
    editorMode: "Editor mode",
    active: "Active",
    idle: "Idle",
    editorModeNote: "Template editing state",
    broadcastSafety: "Broadcast safety",
    broadcastSafetyValue: "Confirmed",
    broadcastSafetyNote: "Mass send requires an extra checkpoint",
    variableHelp: "Variable help",
    variableHelpNote: "Common placeholders available to the admin",
    workflow: "Notification workflow",
    title: "Edit the template, preview the result, then confirm before any broadcast",
    desc: "This page separates template editing from sending, so high-risk broadcast actions always feel deliberate.",
    noTemplatesTitle: "No templates found",
    noTemplatesDesc: "No notification templates are available yet.",
    editor: "Template editor",
    preview: "Preview",
    chooseTitle: "Choose a template to start",
    chooseDesc: "Select a template to edit its subject, body, preview, and broadcast options.",
    broadcastTitle: "Broadcast to all students?",
    broadcastDesc: "This sends the selected template to all enrolled students. Make sure the content and variables are correct first.",
    emptyBody: "<p>No email body yet.</p>"
  },
  settings: {
    courseCopy: "Course copy",
    courseCopyValue: "4 fields",
    courseCopyNote: "Public-facing bilingual course details",
    deliverySetup: "Delivery setup",
    deliverySetupValue: "SMTP",
    deliverySetupNote: "Email infrastructure for student messaging",
    payments: "Payments",
    paymentsValue: "Paymob",
    paymentsNote: "Sensitive production credential area",
    saveFlow: "Save flow",
    saveFlowValue: "Split by area",
    saveFlowNote: "Safer updates with clearer boundaries",
    guidance: "Settings guidance",
    title: "Separate content, delivery, and credentials so each save feels safe",
    desc: "This page is organized around operational boundaries. Course settings affect the public product surface, while system settings affect delivery and payments. Keeping them visually separate lowers configuration risk.",
    courseSettings: "Course settings",
    publicPresentation: "Public course presentation",
    publicDesc: "Update the bilingual title and description shown across the product.",
    emailDelivery: "Email delivery",
    smtpConfig: "SMTP configuration",
    sensitiveCredentials: "Sensitive credentials",
    secretKeys: "Payments and secret keys",
    secretDesc: "Only update these values when rotating credentials or switching environments.",
    smtpHost: "SMTP host",
    smtpUser: "SMTP user",
    smtpPassword: "SMTP password",
    paymobKey: "Paymob API key",
    saving: "Saving..."
  }
};

const ar: typeof en = {
  common: {
    all: "الكل",
    active: "نشط",
    inactive: "غير نشط",
    amount: "المبلغ",
    awaitingAdmin: "بانتظار المسؤول",
    bodyHtml: "محتوى HTML",
    broadcast: "إرسال جماعي",
    cancel: "إلغاء",
    code: "الكود",
    completed: "مكتمل",
    confirmBroadcast: "تأكيد الإرسال",
    coupon: "قسيمة",
    createCoupon: "إنشاء قسيمة",
    createFirstLesson: "إنشاء أول درس",
    delete: "حذف",
    draft: "مسودة",
    edit: "تعديل",
    editDetails: "تعديل التفاصيل",
    editPackage: "تعديل الباقة",
    egp: "جنيه",
    failed: "فشل",
    loading: "جار التحميل...",
    markPaid: "تأكيد الدفع",
    noSubject: "لا يوجد عنوان بعد",
    pending: "معلق",
    published: "منشور",
    ready: "جاهز",
    refunded: "مسترد",
    resolved: "تم الحل",
    savePackage: "حفظ الباقة",
    sendReply: "إرسال الرد",
    sending: "جار الإرسال...",
    status: "الحالة",
    subject: "العنوان",
    updating: "جار التحديث...",
    used: "استخدام"
  },
  lessons: {
    totalLessons: "إجمالي الدروس",
    filteredLessons: "دروس القسم المحدد",
    fullWorkspace: "عبر مساحة الدورة بالكامل",
    filteredWorkspace: "مفلترة حسب القسم النشط",
    videoReady: "الفيديو جاهز",
    readyNote: "دروس جاهزة للطلاب",
    processingNow: "قيد المعالجة",
    processingNote: "ملفات رفع يتم تجهيزها الآن",
    needsPublishing: "تحتاج للنشر",
    needsPublishingNote: "دروس مسودة لا تظهر للطلاب بعد",
    workflow: "سير العمل",
    workflowSteps: [
      "١. اختر قسما لتضييق مساحة العمل.",
      "٢. أنشئ درسا أو اختر درسا موجودا.",
      "٣. ارفع فيديو الدرس وأضف المرفقات.",
      "٤. انشر الدرس فقط عندما يصبح جاهزا بالكامل."
    ],
    workspace: "مساحة إدارة الدروس",
    manageSection: "إدارة دروس القسم النشط",
    manageLibrary: "إدارة مكتبة الدروس بالكامل",
    workspaceDesc: "اجمع بنية الأقسام، حالة النشر، جاهزية الفيديو، وإدارة الموارد في مكان واحد حتى تبقى العمليات سهلة القراءة.",
    showAll: "عرض الكل",
    newLesson: "+ درس جديد",
    emptySectionTitle: "لا توجد دروس في هذا القسم بعد",
    emptyAllTitle: "لم يتم إنشاء دروس بعد",
    emptySectionDesc: "هذا القسم جاهز للمحتوى، لكن لم تتم إضافة أي دروس إليه بعد.",
    emptyAllDesc: "أنشئ أول درس لبدء بناء مسار تعلم الطالب.",
    selectedLesson: "الدرس المحدد",
    noVideo: "لا يوجد فيديو",
    processing: "قيد المعالجة",
    needsReview: "يحتاج مراجعة",
    noDuration: "لا توجد مدة بعد",
    noSection: "بدون قسم",
    unsectioned: "غير مصنف",
    noDrip: "بدون تأخير",
    unlocksAfter: "يفتح بعد {{days}} يوم",
    order: "الترتيب",
    duration: "المدة",
    release: "الإتاحة",
    visibility: "الظهور",
    immediate: "فوري",
    dayDrip: "تأخير {{days}} يوم",
    editSettings: "تعديل إعدادات الدرس",
    videoUpload: "رفع الفيديو",
    replaceVideo: "استبدال أو إضافة فيديو الدرس",
    uploadDesc: "ارفع تسجيل الدرس النهائي هنا. قد تستغرق المعالجة بعض الوقت قبل أن يصبح الدرس جاهزا بالكامل.",
    videoFile: "ملف الفيديو",
    uploadProgress: "تقدم الرفع",
    cancelUpload: "إلغاء الرفع",
    pickLessonTitle: "اختر درسا للمتابعة",
    pickLessonDesc: "اختر درسا من مساحة العمل لرفع الوسائط ومراجعة حالته وإدارة مرفقاته."
  },
  orders: {
    totalOrders: "إجمالي الطلبات",
    totalOrdersNote: "ضمن موجز الإدارة الحالي",
    pendingReview: "بانتظار المراجعة",
    pendingReviewNote: "طلبات لا تزال بانتظار تأكيد الدفع",
    failedNote: "مدفوعات غالبا تحتاج متابعة دعم",
    capturedRevenue: "الإيراد المحصل",
    capturedRevenueNote: "الطلبات المكتملة فقط",
    revenueOps: "عمليات الإيراد",
    title: "راجع الاستثناءات أولا ثم الطلبات السليمة",
    desc: "هذه المساحة مهيأة لمتابعة المدفوعات. يجب أن تظهر الطلبات المعلقة والفاشلة بسرعة حتى لا تخفيها الطلبات المكتملة.",
    allOrders: "كل الطلبات",
    exportCsv: "تصدير CSV",
    emptyTitle: "لا توجد طلبات في هذا العرض",
    emptyDesc: "لا توجد طلبات تطابق الفلتر الحالي. جرب الرجوع إلى كل الطلبات أو راجع العناصر المعلقة أولا.",
    selectedOrder: "الطلب المحدد",
    orderId: "رقم الطلب",
    date: "التاريخ",
    recommended: "طريقة التعامل المقترحة",
    recommendedDesc: "أكد الدفع فقط بعد التحقق الخارجي من لوحة الدفع أو مسار الدعم. أبق المدفوعات الفاشلة ظاهرة حتى يتمكن الفريق من المتابعة بوضوح.",
    pickTitle: "اختر طلبا للمراجعة",
    pickDesc: "اختر طلبا لمراجعة المبلغ والحالة والخطوة التالية."
  },
  pricing: {
    activePackages: "الباقات النشطة",
    activePackagesNote: "العرض العام الظاهر للطلاب حاليا",
    activeCoupons: "القسائم النشطة",
    activeCouponsNote: "خصومات مباشرة قابلة للاستخدام في الدفع",
    couponRevenue: "إيراد القسائم",
    couponRevenueNote: "الإيراد الناتج عن استخدام القسائم",
    pricingSurfaces: "مساحات التسعير",
    pricingSurfacesValue: "مساحتان",
    pricingSurfacesNote: "تتم إدارة الباقات والقسائم بشكل منفصل",
    operations: "عمليات التسعير",
    title: "حافظ على وضوح العرض الأساسي ثم أضف القسائم بوعي",
    desc: "تفصل هذه الصفحة إدارة الباقات عن القسائم حتى يبقى العرض العام سهل الفهم ولا تختلط الخصومات بقرارات السعر الأساسي.",
    coursePackages: "باقات الدورة",
    publicOptions: "خيارات التسعير العامة",
    newPackage: "+ باقة جديدة",
    noPackages: "لا توجد باقات",
    noPackagesDesc: "لم يتم إعداد أي باقات بعد. أضف أول باقة لتعريف العرض العام.",
    sort: "ترتيب",
    couponPerformance: "أداء القسائم",
    noCoupons: "لا توجد قسائم",
    noCouponsDesc: "لا توجد قسائم نشطة بعد. أنشئ قسيمة عند الحاجة إلى عرض ترويجي أو استعادة طالب متردد.",
    revenueGenerated: "الإيراد الناتج",
    createCouponTitle: "أضف خصما موجها دون تغيير العرض الأساسي",
    discountType: "نوع الخصم",
    discountValue: "قيمة الخصم",
    maxUses: "الحد الأقصى للاستخدام",
    expiryDate: "تاريخ الانتهاء",
    percentage: "نسبة مئوية",
    fixed: "قيمة ثابتة",
    percentageOff: "خصم {{value}}%",
    fixedOff: "خصم {{value}} جنيه",
    editPackage: "تعديل الباقة",
    createPackage: "إنشاء باقة",
    packageDialogDesc: "حدث العرض العام دون خلطه بمنطق القسائم.",
    titleEn: "العنوان بالإنجليزية",
    titleAr: "العنوان بالعربية",
    descriptionEn: "الوصف بالإنجليزية",
    descriptionAr: "الوصف بالعربية",
    priceEgp: "السعر بالجنيه",
    sortOrder: "ترتيب الظهور"
  },
  analytics: {
    revenue: "الإيراد",
    revenueNote: "ملخص موجز المدفوعات الحالي",
    completedNote: "مدفوعات ناجحة في الموجز",
    failedNote: "معاملات غالبا تحتاج مراجعة",
    insightWindow: "نافذة التحليل",
    insightWindowNote: "فترة تحليلات التعلم الحالية",
    view: "عرض التحليلات",
    title: "ابدأ بالقرارات وليس الرسوم الخام",
    desc: "تفصل هذه اللوحات أداء التعلم عن متابعة المدفوعات حتى تبقى الرؤى وعمليات الإيراد واضحة.",
    topLessons: "أفضل الدروس أداء",
    noTopTitle: "لا توجد دروس متصدرة بعد",
    noTopDesc: "لا توجد تحليلات دروس متاحة لهذه الفترة بعد.",
    completion: "إكمال",
    avgWatch: "متوسط المشاهدة",
    dropOff: "دروس بها انسحاب",
    noDropTitle: "لا توجد مخاطر انسحاب",
    noDropDesc: "لم يتم إرجاع دروس بها انسحاب لهذه الفترة.",
    avgExit: "متوسط نقطة الخروج",
    paymentReview: "مراجعة المدفوعات",
    paymentTitle: "أبق الاستثناءات واضحة وقابلة للتصرف",
    noPaymentsTitle: "لا توجد مدفوعات في هذا العرض",
    noPaymentsDesc: "لا توجد مدفوعات تطابق الفلتر الحالي.",
    selectedPayment: "الدفعة المحددة",
    discount: "الخصم",
    transaction: "المعاملة",
    none: "لا يوجد",
    notAvailable: "غير متاح",
    pickPaymentTitle: "اختر دفعة للمراجعة",
    pickPaymentDesc: "اختر دفعة لمراجعة استخدام القسيمة وتفاصيل المعاملة والخطوات التالية."
  },
  tickets: {
    openTickets: "التذاكر المفتوحة",
    openTicketsNote: "تحتاج متابعة دعم نشطة",
    resolvedNote: "محادثات دعم مكتملة",
    awaitingAdminNote: "آخر رسالة جاءت من الطالب",
    currentView: "العرض الحالي",
    currentViewNote: "قائمة الدعم المفلترة",
    supportQueue: "قائمة الدعم",
    title: "ضع محادثات الطلاب العاجلة أولا واجعل الرد سريعا",
    allTickets: "كل التذاكر",
    emptyTitle: "لا توجد تذاكر للمراجعة",
    emptyDesc: "لا توجد تذاكر في هذا العرض حاليا.",
    updated: "آخر تحديث",
    triageNotes: "ملاحظات الفرز",
    triage: [
      "ابدأ بالتذاكر المفتوحة التي جاءت آخر رسالة فيها من الطالب.",
      "لا تغلق المحادثة إلا بعد الرد على سؤال الطالب بوضوح.",
      "استخدم لوحة المحادثة لكتابة ردود مختصرة وآمنة تشغيليا."
    ],
    details: "تفاصيل التذكرة",
    reply: "الرد",
    replyPlaceholder: "اكتب ردا واضحا ومفيدا",
    resolveTicket: "حل التذكرة",
    noMessages: "لا توجد رسائل بعد."
  },
  audit: {
    visibleEntries: "العناصر الظاهرة",
    visibleEntriesNote: "النتائج الحالية في هذه المساحة",
    totalEntries: "إجمالي السجلات",
    totalEntriesNote: "كل أحداث التدقيق القادمة من الواجهة البرمجية",
    uniqueActors: "المسؤولون الفريدون",
    uniqueActorsNote: "مسؤولون لديهم نشاط مسجل",
    expandedRow: "صف مفتوح",
    expandedRowNote: "بيانات تفصيلية مفتوحة حاليا",
    workspace: "مساحة التدقيق",
    title: "راجع من غيّر ماذا وافتح التفاصيل عند الحاجة فقط",
    desc: "هذه الصفحة مصممة للتحقيق السريع أولا ثم التفاصيل ثانيا حتى يبقى سجل الأحداث سهل القراءة.",
    searchLabel: "ابحث عن مسؤول أو إجراء أو هدف",
    searchPlaceholder: "ابحث في سجل التدقيق",
    noMatchTitle: "لا توجد أحداث مطابقة",
    noMatchDesc: "لا توجد سجلات تدقيق تطابق البحث الحالي. جرب بحثا أوسع أو امسح الفلتر.",
    time: "الوقت",
    actor: "المسؤول",
    action: "الإجراء",
    target: "الهدف",
    metadata: "البيانات التفصيلية"
  },
  notifications: {
    templates: "القوالب",
    templatesNote: "قوالب إشعارات قابلة لإعادة الاستخدام",
    editorMode: "وضع التحرير",
    active: "نشط",
    idle: "غير نشط",
    editorModeNote: "حالة تحرير القالب",
    broadcastSafety: "أمان الإرسال",
    broadcastSafetyValue: "مؤكد",
    broadcastSafetyNote: "الإرسال الجماعي يحتاج خطوة تأكيد إضافية",
    variableHelp: "مساعدة المتغيرات",
    variableHelpNote: "متغيرات شائعة متاحة للمسؤول",
    workflow: "سير عمل الإشعارات",
    title: "حرر القالب وعاينه ثم أكد قبل أي إرسال جماعي",
    desc: "تفصل هذه الصفحة التحرير عن الإرسال حتى تبدو إجراءات الإرسال عالية التأثير مقصودة وآمنة.",
    noTemplatesTitle: "لا توجد قوالب",
    noTemplatesDesc: "لا توجد قوالب إشعارات متاحة بعد.",
    editor: "محرر القالب",
    preview: "المعاينة",
    chooseTitle: "اختر قالبا للبدء",
    chooseDesc: "اختر قالبا لتعديل العنوان والمحتوى والمعاينة وخيارات الإرسال.",
    broadcastTitle: "إرسال إلى كل الطلاب؟",
    broadcastDesc: "سيتم إرسال القالب المحدد إلى كل الطلاب المسجلين. تأكد من المحتوى والمتغيرات أولا.",
    emptyBody: "<p>لا يوجد محتوى بريد بعد.</p>"
  },
  settings: {
    courseCopy: "محتوى الدورة",
    courseCopyValue: "٤ حقول",
    courseCopyNote: "تفاصيل الدورة الثنائية اللغة الظاهرة للطلاب",
    deliverySetup: "إعداد الإرسال",
    deliverySetupValue: "SMTP",
    deliverySetupNote: "بنية البريد الإلكتروني لرسائل الطلاب",
    payments: "المدفوعات",
    paymentsValue: "Paymob",
    paymentsNote: "منطقة بيانات إنتاج حساسة",
    saveFlow: "مسار الحفظ",
    saveFlowValue: "مقسم حسب المنطقة",
    saveFlowNote: "تحديثات أكثر أمانا بحدود واضحة",
    guidance: "إرشادات الإعدادات",
    title: "افصل المحتوى والتسليم وبيانات الاعتماد حتى يكون كل حفظ آمنا",
    desc: "تنظم هذه الصفحة الإعدادات حسب حدود التشغيل. إعدادات الدورة تؤثر على واجهة المنتج، بينما إعدادات النظام تؤثر على البريد والمدفوعات.",
    courseSettings: "إعدادات الدورة",
    publicPresentation: "عرض الدورة العام",
    publicDesc: "حدث العنوان والوصف باللغتين كما يظهران في المنتج.",
    emailDelivery: "إرسال البريد",
    smtpConfig: "إعداد SMTP",
    sensitiveCredentials: "بيانات اعتماد حساسة",
    secretKeys: "المدفوعات والمفاتيح السرية",
    secretDesc: "حدث هذه القيم فقط عند تدوير المفاتيح أو تبديل البيئة.",
    smtpHost: "مضيف SMTP",
    smtpUser: "مستخدم SMTP",
    smtpPassword: "كلمة مرور SMTP",
    paymobKey: "مفتاح Paymob API",
    saving: "جار الحفظ..."
  }
};

export const getAdminUiCopy = (locale: AppLocale) => (locale === "ar" ? ar : en);
